### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [rcoh/rcoh-dot-me-v2#5]
The rcoh.me website is inaccessible over IPv6.

**Comment by rcoh** [comment]
Weird. Thank you for letting me know I'll look into it.

**Comment by rcoh** [comment]
Seems like my hosting provider doesn't support it. Will be sure to add support for it when they do

**Comment by rcoh** [comment]
I've enabled IPv6 via netlify. Thanks!

**Comment by tambry** [comment]
Thanks for keeping this in mind, doing it so quickly after they enabled IPv6 and letting me know about it!  
Unfortunately I'm not actually seeing any AAAA records on your website's domain.

**Comment by rcoh** [comment]
Ah you're right. Fixed, `curl -6 https://rcoh.me` works now

**Comment by tambry** [comment]
Yep, working now. 👍   
You forgot to add the AAAA record for `www.rcoh.me` though.
