### ISSUE TITLE
Maybe there is a slip of the pen in your post?

### ISSUE THREAD

**Issue by bringyou** [rcoh/rcoh-dot-me-v2#6]
I found something maybe a slip of the pen in your post [why-you-can-have-a-million-go-routines-but-only-1000-java-threads](https://github.com/rcoh/rcoh-dot-me-v2/blob/master/content/posts/why-you-can-have-a-million-go-routines-but-only-1000-java-threads.md), it said:
> While I'm not going to get into the internal details here (they're more than enough for their own posts and others have written about it at length), the upshot is that a new goroutine will have a stack of only about 4KB. With 4KB per stack, you can put 2.5 million goroutines in a gigabyte of RAM -- a huge improvement over Java's 1MB per thread

The number of goroutines here is 2.5 million, but should it be 0.25 million?
BTW, thanks for your great post.

**Comment by rcoh** [comment]
I think you're right! Thanks for reporting, I'll fix. Or feel free to see
send a PR and I'll merge.

**Comment by bringyou** [comment]
thank you, I have created one #7
